In [1]:
import pandas as pd
import numpy as np

# •	Extraction

In [2]:
# Load datasets from Excel sheets
xls= pd.ExcelFile("CRM_Analytics_Datasets.xlsx") 
xls.sheet_names

['contacts', 'deals', 'activities']

In [3]:
contacts_df = pd.read_excel(xls, sheet_name="contacts")
contacts_df.head()

,contact_id,first_name,last_name,email,company_name,created_date,lead_source
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website
1,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website
2,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign
3,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral
4,5,Jessica,Dougherty,matthewsmith@murphy.com,Hudson-Owens,2025-08-11,Referral

In [4]:
deals_df = pd.read_excel(xls, sheet_name="deals")
deals_df.head()

,deal_id,contact_id,sales_rep,deal_amount,deal_stage,created_date,closed_date
0,1,3226,Brian Haynes,43491,Prospecting,2025-01-13,2025-10-30
1,2,4350,Brian Williams,18754,Qualified,2025-05-20,2025-10-30
2,3,2520,Kristina Winters,39536,Negotiation,2025-03-05,2025-10-30
3,4,1263,Nancy Hall,1962,Closed Lost,2025-07-02,2025-10-30
4,5,1195,John Rollins,42169,Closed Won,2025-07-02,2025-10-30

In [5]:
activities_df = pd.read_excel(xls, sheet_name="activities")
activities_df.head()

,activity_id,contact_id,sales_rep,activity_type,contact_time,response_time
0,1,294,Elizabeth Collins,Demo,2024-12-04 23:07:52,2025-10-31 17:39:11
1,2,218,Jerry Edwards,Demo,2025-02-05 01:51:06,2025-10-31 17:37:10
2,3,4688,Harry Valdez,Call,2025-10-12 14:38:30,2025-10-31 17:36:50
3,4,3262,Anthony Sullivan,Meeting,2025-07-17 16:47:52,2025-10-31 17:39:34
4,5,2402,Virginia Wood,Call,2025-08-02 13:13:19,2025-10-31 17:41:05

In [6]:
# Building Leads sheet
contact_from_deals = deals_df['contact_id'].unique()
leads_df = contacts_df[contacts_df['contact_id'].isin(contact_from_deals)]
leads_df.head()

,contact_id,first_name,last_name,email,company_name,created_date,lead_source
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website
1,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website
2,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign
3,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral
4,5,Jessica,Dougherty,matthewsmith@murphy.com,Hudson-Owens,2025-08-11,Referral

# •	Cleaning & Standardization

In [7]:
# Handling missing vallues
contacts_df.isnull().sum()

contact_id      0
first_name      0
last_name       0
email           0
company_name    0
created_date    0
lead_source     0
dtype: int64

In [8]:
# Handling missing email
contacts_df = contacts_df.dropna(subset=["email"])

In [9]:
deals_df.isnull().sum()

deal_id         0
contact_id      0
sales_rep       0
deal_amount     0
deal_stage      0
created_date    0
closed_date     0
dtype: int64

In [10]:
activities_df.isnull().sum()

activity_id      0
contact_id       0
sales_rep        0
activity_type    0
contact_time     0
response_time    0
dtype: int64

In [11]:
leads_df.isnull().sum()

contact_id      0
first_name      0
last_name       0
email           0
company_name    0
created_date    0
lead_source     0
dtype: int64

In [12]:
# Convert closed_date to datetime
deals_df["closed_date"] = pd.to_datetime(deals_df["closed_date"], errors="coerce")
deals_df["closed_date"]

0      2025-10-30
1      2025-10-30
2      2025-10-30
3      2025-10-30
4      2025-10-30
          ...
9995   2025-10-30
9996   2025-10-30
9997   2025-10-30
9998   2025-10-30
9999   2025-10-30
Name: closed_date, Length: 10000, dtype: datetime64[ns]

In [13]:
# Convert created_date to datetime from contact sheet
contacts_df["created_date"] = pd.to_datetime(contacts_df["created_date"], errors="coerce")
contacts_df["created_date"]

0      2024-04-05
1      2025-10-04
2      2023-10-31
3      2024-07-20
4      2025-08-11
          ...
4995   2024-12-17
4996   2025-09-06
4997   2024-03-23
4998   2025-09-07
4999   2024-06-12
Name: created_date, Length: 5000, dtype: datetime64[ns]

In [14]:
# Convert created_date to datetime from deal sheet
deals_df["created_date"] = pd.to_datetime(deals_df["created_date"], errors="coerce")
deals_df["created_date"]

0      2025-01-13
1      2025-05-20
2      2025-03-05
3      2025-07-02
4      2025-07-02
          ...
9995   2025-01-08
9996   2025-06-22
9997   2025-08-02
9998   2025-08-17
9999   2024-11-19
Name: created_date, Length: 10000, dtype: datetime64[ns]

In [15]:
# Remove duplicate deals
contacts_df = contacts_df.drop_duplicates(subset=["contact_id"])
deals_df = deals_df.drop_duplicates(subset=["deal_id"])
activities_df = activities_df.drop_duplicates(subset=["activity_id"])

In [16]:
# Convert deal_amount to numeric
deals_df["deal_amount"] = pd.to_numeric(deals_df["deal_amount"], errors="coerce")

In [17]:
#Handling deal amount
deals_df["deal_amount"] = deals_df["deal_amount"].fillna(0)

In [18]:
# Ensure IDs are integers
deals_df["deal_id"] = deals_df["deal_id"].astype(int)
contacts_df["contact_id"] = contacts_df["contact_id"].astype(int)
activities_df["activity_id"] = activities_df["activity_id"].astype(int)

In [19]:
# Rename created_date columns according to their sheet names
leads_df.rename(columns={"created_date": "lead_created_date"}, inplace=True)
contacts_df.rename(columns={"created_date": "contact_created_date"}, inplace=True)
deals_df.rename(columns={"created_date": "deal_created_date"}, inplace=True)

In [20]:
#Rename sales_rep column name according to their sheet name
deals_df.rename(columns={"sales_rep": "deals_sales_rep"},  inplace=True)
activities_df.rename(columns={"sales_rep": "activities_sales_rep"},  inplace=True)

In [21]:
deals_df.describe()

,deal_id,contact_id,deal_amount,deal_created_date,closed_date
count,10000.00000,10000.000000,10000.000000,10000,10000
mean,5000.50000,2512.881200,25435.713000,2025-04-29 20:11:28.319999744,2025-10-30 00:00:00
min,1.00000,1.000000,1006.000000,2024-10-30 00:00:00,2025-10-30 00:00:00
25%,2500.75000,1243.000000,13209.500000,2025-01-28 00:00:00,2025-10-30 00:00:00
50%,5000.50000,2526.000000,25444.000000,2025-04-29 00:00:00,2025-10-30 00:00:00
75%,7500.25000,3772.250000,37567.250000,2025-07-31 00:00:00,2025-10-30 00:00:00
max,10000.00000,5000.000000,49999.000000,2025-10-29 00:00:00,2025-10-30 00:00:00
std,2886.89568,1446.868649,14128.614365,NaN,NaN

In [22]:
contacts_df.describe()

        contact_id        contact_created_date
count  5000.000000                        5000
mean   2500.500000  2024-10-30 01:39:56.160000
min       1.000000         2023-10-31 00:00:00
25%    1250.750000         2024-04-30 00:00:00
50%    2500.500000         2024-10-30 00:00:00
75%    3750.250000         2025-05-01 00:00:00
max    5000.000000         2025-10-30 00:00:00
std    1443.520003                         NaN

In [23]:
activities_df.describe()

,activity_id,contact_id,contact_time,response_time
count,7000.000000,7000.000000,7000,7000
mean,3500.500000,2491.736143,2025-05-01 12:45:06.383428608,2025-10-31 17:39:21.275571456
min,1.000000,1.000000,2024-10-31 14:15:10,2025-10-31 17:36:23
25%,1750.750000,1258.000000,2025-01-28 17:16:47,2025-10-31 17:37:52
50%,3500.500000,2489.500000,2025-05-01 15:10:50,2025-10-31 17:39:20
75%,5250.250000,3729.750000,2025-07-31 06:15:20.750000128,2025-10-31 17:40:51
max,7000.000000,5000.000000,2025-10-30 16:30:18,2025-10-31 17:42:23
std,2020.870275,1436.044602,NaN,NaN

In [24]:
leads_df.describe()

        contact_id              lead_created_date
count  4318.000000                           4318
mean   2502.108847  2024-10-29 01:09:41.936081408
min       1.000000            2023-10-31 00:00:00
25%    1243.250000            2024-04-30 00:00:00
50%    2506.500000            2024-10-28 00:00:00
75%    3764.750000            2025-05-01 00:00:00
max    5000.000000            2025-10-30 00:00:00
std    1446.825913                            NaN

# •	Merge HubSpot and Salesforce-style datasets into a unified structure

In [44]:
# Merge leads with contacts
crm_df = leads_df.merge(
    contacts_df,
    on="contact_id",
    how="left"
)

In [45]:
# Merge with deals
crm_df = crm_df.merge(
    deals_df,
    on="contact_id",
    how="left"
)

In [46]:
# Merge with activities
crm_df = crm_df.merge(
    activities_df,
    on="contact_id",
    how="left"
)

In [47]:
# Final Unified CRM DataFrame
crm_df.head()

,contact_id,first_name_x,last_name_x,email_x,company_name_x,lead_created_date,lead_source_x,first_name_y,last_name_y,email_y,...,deals_sales_rep,deal_amount,deal_stage,deal_created_date,closed_date,activity_id,activities_sales_rep,activity_type,contact_time,response_time
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,Kevin,Gibson,lawsonmichael@adams.biz,...,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08
1,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,Kevin,Gibson,lawsonmichael@adams.biz,...,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15
2,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,Kevin,Gibson,lawsonmichael@adams.biz,...,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26
3,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,Kevin,Gibson,lawsonmichael@adams.biz,...,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21
4,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,Kevin,Gibson,lawsonmichael@adams.biz,...,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26

In [48]:
# Drop duplicate columns
crm_df = crm_df.drop(columns=[
    "first_name_y",
    "last_name_y",
    "email_y",
    "lead_source_y",
    "company_name_y"
])

In [49]:
# Rename _x columns to clean names
crm_df = crm_df.rename(columns={
    "first_name_x": "first_name",
    "last_name_x": "last_name",
    "email_x": "email",
    "company_name_x": "company_name",
    "lead_source_x": "lead_source"
})

In [50]:
crm_df.head()

,contact_id,first_name,last_name,email,company_name,lead_created_date,lead_source,contact_created_date,deal_id,deals_sales_rep,deal_amount,deal_stage,deal_created_date,closed_date,activity_id,activities_sales_rep,activity_type,contact_time,response_time
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08
1,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15
2,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26
3,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21
4,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,20970,Closed Lost,2025-06-16,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26

In [51]:
print(crm_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16576 entries, 0 to 16575
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   contact_id            16576 non-null  int64
 1   first_name            16576 non-null  object
 2   last_name             16576 non-null  object
 3   email                 16576 non-null  object
 4   company_name          16576 non-null  object
 5   lead_created_date     16576 non-null  datetime64[ns]
 6   lead_source           16576 non-null  object
 7   contact_created_date  16576 non-null  datetime64[ns]
 8   deal_id               16576 non-null  int32
 9   deals_sales_rep       16576 non-null  object
 10  deal_amount           16576 non-null  int64
 11  deal_stage            16576 non-null  object
 12  deal_created_date     16576 non-null  datetime64[ns]
 13  closed_date           16576 non-null  datetime64[ns]
 14  activity_id           14213 non-null  float64
 15  activities_sales_rep  14213 non-null  object
 16  activity_type         14213 non-null  object
 17  contact_time          14213 non-null  datetime64[ns]
 18  response_time         14213 non-null  datetime64[ns]
dtypes: datetime64[ns](6), float64(1), int32(1), int64(2), object(9)
memory usage: 2.3+ MB
None

# Computed columns

In [53]:
# Lead Response Time in hours
crm_df['lead_response_time_hours'] = (
    crm_df['response_time'] - crm_df['contact_time']
).dt.total_seconds() / 3600
crm_df['lead_response_time_hours']

0        1291.715833
1        2467.783056
2        1583.104167
3        3783.659444
4        1245.641389
            ...
16571    5059.498056
16572    5059.498056
16573    5059.498056
16574    5059.498056
16575    7172.702778
Name: lead_response_time_hours, Length: 16576, dtype: float64

In [55]:
#Deal Conversion Rate per Sales Representative
crm_df.columns = crm_df.columns.str.strip().str.lower()

In [56]:
closed_won_flag= crm_df['deal_stage'].eq('Closed Won').astype(int)
closed_won_flag

0        0
1        0
2        0
3        0
4        0
        ..
16571    1
16572    0
16573    0
16574    0
16575    0
Name: deal_stage, Length: 16576, dtype: int32

In [60]:
closed_won_total= closed_won_flag.groupby(crm_df["deals_sales_rep"]).transform("sum")
total_deals= crm_df.groupby("deals_sales_rep")["contact_id"].transform("count")
       
crm_df["conversion_rate"] = closed_won_total/total_deals

In [61]:
crm_df.head(50)

,contact_id,first_name,last_name,email,company_name,lead_created_date,lead_source,contact_created_date,deal_id,deals_sales_rep,...,deal_stage,deal_created_date,closed_date,activity_id,activities_sales_rep,activity_type,contact_time,response_time,lead_response_time_hours,conversion_rate
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08,1291.715833,0.0
1,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15,2467.783056,0.0
2,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26,1583.104167,0.0
3,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21,3783.659444,0.0
4,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26,1245.641389,0.0
5,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,Closed Lost,2025-06-16,2025-10-30,6847.0,Daniel Ryan,Meeting,2025-10-08 04:28:35,2025-10-31 17:39:19,565.178889,0.0
6,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08,1291.715833,0.0
7,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15,2467.783056,0.0
8,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26,1583.104167,0.0
9,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21,3783.659444,0.0
10,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26,1245.641389,0.0
11,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,Negotiation,2024-11-03,2025-10-30,6847.0,Daniel Ryan,Meeting,2025-10-08 04:28:35,2025-10-31 17:39:19,565.178889,0.0
12,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website,2025-10-04,7778,Cynthia Chapman,...,Qualified,2025-04-12,2025-10-30,2266.0,Dominic Klein,Call,2025-05-17 17:09:03,2025-10-31 17:42:01,4008.549444,0.0
13,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website,2025-10-04,7778,Cynthia Chapman,...,Qualified,2025-04-12,2025-10-30,2680.0,Jesus Williams PhD,Email,2025-06-21 10:06:06,2025-10-31 17:36:24,3175.505000,0.0
14,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,5506,Jordan Herrera,...,Closed Won,2025-08-07,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,1.0
15,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,5506,Jordan Herrera,...,Closed Won,2025-08-07,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,1.0
16,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,6919,Dominique Weaver,...,Prospecting,2024-11-12,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,0.0
17,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,6919,Dominique Weaver,...,Prospecting,2024-11-12,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,0.0
18,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,7806,Tami Pierce,...,Proposal,2024-12-27,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,0.0
19,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,7806,Tami Pierce,...,Proposal,2024-12-27,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,0.0
20,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,9399,Gerald Yang,...,Negotiation,2024-11-11,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,0.0
21,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,9399,Gerald Yang,...,Negotiation,2024-11-11,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,0.0
22,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral,2024-07-20,1869,Caroline Warner,...,Proposal,2025-05-15,2025-10-30,1332.0,Christopher Ramsey,Meeting,2025-03-06 21:29:21,2025-10-31 17:39:40,5732.171944,0.0
23,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral,2024-07-20,1869,Caroline Warner,...,Proposal,2025-05-15,2025-10-30,5689.0,Pamela Lang,Meeting,2025-07-27 05:03:36,2025-10-31 17:40:44,2316.618889,0.0
24,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral,2024-07-20,5308,Matthew Huffman,...,Negotiation,2025-06-01,2025-10-30,1332.0,Christopher Ramsey,Meeting,2025-03-06 21:29:21,2025-10-31 17:39:40,5732.171944,0.0
25,4,Christopher,Guerra,davidperry@johns-powell.org,Kelly and Sons,2024-07-20,Referral,2024-07-20,5308,Matthew Huffman,...,Negotiation,2025-06-01,2025-10-30,5689.0,Pamela Lang,Meeting,2025-07-27 05:03:36,2025-10-31 17:40:44,2316.618889,0.0
26,5,Jessica,Dougherty,matthewsmith@murphy.com,Hudson-Owens,2025-08-11,Referral,2025-08-11,2374,Stephen Carroll,...,Prospecting,2025-05-24,2025-10-30,NaN,NaN,NaN,NaT,NaT,NaN,0.0
27,7,Timothy,Garner,alichase@hodges.org,Montoya-Gutierrez,2024-08-21,Website,2024-08-21,1508,Amy Klein,...,Negotiation,2025-07-05,2025-10-30,NaN,NaN,NaN,NaT,NaT,NaN,0.0
28,7,Timothy,Garner,alichase@hodges.org,Montoya-Gutierrez,2024-08-21,Website,2024-08-21,8956,Angela Pace,...,Closed Won,2025-06-06,2025-10-30,NaN,NaN,NaN,NaT,NaT,NaN,1.0
29,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,1728,Katherine Mcbride,...,Proposal,2025-05-04,2025-10-30,2607.0,Mrs. Angela Jones DVM,Demo,2025-03-07 10:50:27,2025-10-31 17:37:59,5718.792222,0.0
30,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,1728,Katherine Mcbride,...,Proposal,2025-05-04,2025-10-30,3141.0,Miguel Gross,Demo,2025-08-13 05:55:11,2025-10-31 17:41:48,1907.776944,0.0
31,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,1728,Katherine Mcbride,...,Proposal,2025-05-04,2025-10-30,4536.0,Sarah Harris,Call,2025-07-28 22:37:59,2025-10-31 17:41:10,2275.053056,0.0
32,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,2060,Katie Stephens,...,Closed Won,2025-03-30,2025-10-30,2607.0,Mrs. Angela Jones DVM,Demo,2025-03-07 10:50:27,2025-10-31 17:37:59,5718.792222,1.0
33,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,2060,Katie Stephens,...,Closed Won,2025-03-30,2025-10-30,3141.0,Miguel Gross,Demo,2025-08-13 05:55:11,2025-10-31 17:41:48,1907.776944,1.0
34,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,2060,Katie Stephens,...,Closed Won,2025-03-30,2025-10-30,4536.0,Sarah Harris,Call,2025-07-28 22:37:59,2025-10-31 17:41:10,2275.053056,1.0
35,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,8783,Bryan Aguilar,...,Proposal,2024-12-07,2025-10-30,2607.0,Mrs. Angela Jones DVM,Demo,2025-03-07 10:50:27,2025-10-31 17:37:59,5718.792222,0.0
36,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,8783,Bryan Aguilar,...,Proposal,2024-12-07,2025-10-30,3141.0,Miguel Gross,Demo,2025-08-13 05:55:11,2025-10-31 17:41:48,1907.776944,0.0
37,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,8783,Bryan Aguilar,...,Proposal,2024-12-07,2025-10-30,4536.0,Sarah Harris,Call,2025-07-28 22:37:59,2025-10-31 17:41:10,2275.053056,0.0
38,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,9708,Nathan Moore,...,Closed Won,2025-08-09,2025-10-30,2607.0,Mrs. Angela Jones DVM,Demo,2025-03-07 10:50:27,2025-10-31 17:37:59,5718.792222,1.0
39,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,9708,Nathan Moore,...,Closed Won,2025-08-09,2025-10-30,3141.0,Miguel Gross,Demo,2025-08-13 05:55:11,2025-10-31 17:41:48,1907.776944,1.0
40,8,Stephen,Jimenez,weberrobert@coleman.com,"Anderson, Brown and Lopez",2024-01-17,Social Media,2024-01-17,9708,Nathan Moore,...,Closed Won,2025-08-09,2025-10-30,4536.0,Sarah Harris,Call,2025-07-28 22:37:59,2025-10-31 17:41:10,2275.053056,1.0
41,9,Christopher,Owens,joshuajensen@yahoo.com,"Williams, Garrison and Lindsey",2025-09-18,Website,2025-09-18,3359,Jose Todd,...,Prospecting,2025-05-10,2025-10-30,185.0,Larry Gregory,Email,2025-08-29 15:49:47,2025-10-31 17:41:25,1513.860556,0.0
42,10,Jack,Stone,kingcaroline@luna.com,"Pearson, Mcclure and Barr",2024-04-29,Social Media,2024-04-29,761,Paul Smith,...,Negotiation,2025-10-18,2025-10-30,6662.0,Sheena Flores,Email,2025-08-05 16:22:02,2025-10-31 17:39:39,2089.293611,0.0
43,10,Jack,Stone,kingcaroline@luna.com,"Pearson, Mcclure and Barr",2024-04-29,Social Media,2024-04-29,4739,Carlos Yates,...,Closed Won,2025-07-31,2025-10-30,6662.0,Sheena Flores,Email,2025-08-05 16:22:02,2025-10-31 17:39:39,2089.293611,1.0
44,10,Jack,Stone,kingcaroline@luna.com,"Pearson, Mcclure and Barr",2024-04-29,Social Media,2024-04-29,6330,Veronica Jones,...,Qualified,2025-08-10,2025-10-30,6662.0,Sheena Flores,Email,2025-08-05 16:22:02,2025-10-31 17:39:39,2089.293611,0.0
45,11,Gloria,King,sandraalvarez@hotmail.com,Miles-Johnson,2024-05-24,Cold Call,2024-05-24,436,Mark Henry,...,Proposal,2025-05-10,2025-10-30,4620.0,Joshua Hines,Meeting,2024-12-13 14:18:52,2025-10-31 17:37:13,7731.305833,0.0
46,11,Gloria,King,sandraalvarez@hotmail.com,Miles-Johnson,2024-05-24,Cold Call,2024-05-24,436,Mark Henry,...,Proposal,2025-05-10,2025-10-30,4747.0,Jeffrey Patel,Demo,2025-08-19 13:32:50,2025-10-31 17:37:52,1756.083889,0.0
47,11,Gloria,King,sandraalvarez@hotmail.com,Miles-Johnson,2024-05-24,Cold Call,2024-05-24,436,Mark Henry,...,Proposal,2025-05-10,2025-10-30,5676.0,Mitchell Vasquez,Meeting,2025-09-05 08:19:13,2025-10-31 17:36:33,1353.288889,0.0
48,11,Gloria,King,sandraalvarez@hotmail.com,Miles-Johnson,2024-05-24,Cold Call,2024-05-24,5287,Anne Webb,...,Closed Won,2024-11-11,2025-10-30,4620.0,Joshua Hines,Meeting,2024-12-13 14:18:52,2025-10-31 17:37:13,7731.305833,1.0
49,11,Gloria,King,sandraalvarez@hotmail.com,Miles-Johnson,2024-05-24,Cold Call,2024-05-24,5287,Anne Webb,...,Closed Won,2024-11-11,2025-10-30,4747.0,Jeffrey Patel,Demo,2025-08-19 13:32:50,2025-10-31 17:37:52,1756.083889,1.0

In [64]:
# Customer Lifetime Value (CLV)
crm_df['clv']=(crm_df.where(crm_df['deal_stage']=='Closed Won')
               .groupby('contact_id')['deal_amount'].transform('sum'))

crm_df['clv'].head(20)

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14    62824.0
15    62824.0
16        NaN
17        NaN
18        NaN
19        NaN
Name: clv, dtype: float64

In [65]:
crm_df['clv']=crm_df['clv'].fillna(0)

In [68]:
crm_df.head(20)

,contact_id,first_name,last_name,email,company_name,lead_created_date,lead_source,contact_created_date,deal_id,deals_sales_rep,...,deal_created_date,closed_date,activity_id,activities_sales_rep,activity_type,contact_time,response_time,lead_response_time_hours,conversion_rate,clv
0,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08,1291.715833,0.0,0.0
1,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15,2467.783056,0.0,0.0
2,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26,1583.104167,0.0,0.0
3,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21,3783.659444,0.0,0.0
4,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26,1245.641389,0.0,0.0
5,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,6963,William Rivers,...,2025-06-16,2025-10-30,6847.0,Daniel Ryan,Meeting,2025-10-08 04:28:35,2025-10-31 17:39:19,565.178889,0.0,0.0
6,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,219.0,Erin Allen,Email,2025-09-07 21:54:11,2025-10-31 17:37:08,1291.715833,0.0,0.0
7,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,363.0,Stephanie Ortiz,Meeting,2025-07-20 21:53:16,2025-10-31 17:40:15,2467.783056,0.0,0.0
8,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,3068.0,Nicholas Howard,Demo,2025-08-26 18:34:11,2025-10-31 17:40:26,1583.104167,0.0,0.0
9,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,3366.0,Samantha Avery,Demo,2025-05-27 01:58:47,2025-10-31 17:38:21,3783.659444,0.0,0.0
10,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,5430.0,Isabella Warren,Call,2025-09-09 20:00:57,2025-10-31 17:39:26,1245.641389,0.0,0.0
11,1,Kevin,Gibson,lawsonmichael@adams.biz,"King, Scott and Richardson",2024-04-05,Website,2024-04-05,9275,Bethany Anderson,...,2024-11-03,2025-10-30,6847.0,Daniel Ryan,Meeting,2025-10-08 04:28:35,2025-10-31 17:39:19,565.178889,0.0,0.0
12,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website,2025-10-04,7778,Cynthia Chapman,...,2025-04-12,2025-10-30,2266.0,Dominic Klein,Call,2025-05-17 17:09:03,2025-10-31 17:42:01,4008.549444,0.0,0.0
13,2,Zachary,Henderson,johnsummers@reid.org,Kirby PLC,2025-10-04,Website,2025-10-04,7778,Cynthia Chapman,...,2025-04-12,2025-10-30,2680.0,Jesus Williams PhD,Email,2025-06-21 10:06:06,2025-10-31 17:36:24,3175.505000,0.0,0.0
14,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,5506,Jordan Herrera,...,2025-08-07,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,1.0,62824.0
15,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,5506,Jordan Herrera,...,2025-08-07,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,1.0,62824.0
16,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,6919,Dominique Weaver,...,2024-11-12,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,0.0,0.0
17,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,6919,Dominique Weaver,...,2024-11-12,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,0.0,0.0
18,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,7806,Tami Pierce,...,2024-12-27,2025-10-30,1925.0,Isaac Atkinson,Meeting,2025-04-09 15:57:42,2025-10-31 17:40:08,4921.707222,0.0,0.0
19,3,Diana,Lin,stephen49@wang-smith.com,"Rodriguez, Cohen and Washington",2023-10-31,Email Campaign,2023-10-31,7806,Tami Pierce,...,2024-12-27,2025-10-30,6960.0,Kenneth Williams,Email,2024-12-20 02:43:56,2025-10-31 17:36:37,7574.878056,0.0,0.0

In [69]:
#Follwing code are to transfer cleaned file to SQL

from sqlalchemy import create_engine
# MySQL credentials

username = 'root'

password = '123456789'

host = 'localhost'       

port = '3306'            # default MySQL port

database = 'CRM_analysis_database'


# Creating the SQLAlchemy engine

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')


# Read CSV file

#df = pd.read_csv('D:\sabiha\study\Fortray\workshop\assignment_pension\pension_dataset_20000.csv')


# To Import the data into MySQL 

crm_df.to_sql(
    name="Marged_CRM_record",
    con=engine,
    if_exists="replace",
    index=False
)


print("Data imported successfully!")

Data imported successfully!

C:\Users\User\AppData\Local\Temp\ipykernel_3884\2752798048.py:29: UserWarning: The provided table name 'Marged_CRM_record' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  crm_df.to_sql(

In [70]:
# Save to CSV for MySQL import
csv_path = "cleaned_CRM_marged_analysis.csv"
crm_df.to_csv(csv_path, index=False)

print("CSV file created for MySQL import:", csv_path)

CSV file created for MySQL import: cleaned_CRM_marged_analysis.csv

In [71]:
import os
print(os.getcwd())

C:\Users\User